version: '3'
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - postgres
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: usertest
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - 8083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: supersenha
    logging:
      driver: none